name = "encrypted group"
author = "encode42"
version = "1.3.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c8b9d4cd09bfbb73e09cf4aeb475f5954f5b23227006e596fda22c6fc7e98ece"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
