name = "encrypted group"
author = "encode42"
version = "1.5.3-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8f4d00ee71c27a4eb731160de9f24de270733d5c5a96845b62957df85a2c5c57"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
