name = "encrypted group"
author = "encode42"
version = "1.3.1-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1db199f302265ceb417011d09a4113a7a027db21474c6d935e93edf56ae7218b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
