name = "encrypted group"
author = "encode42"
version = "1.6.1-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b0a55eb499523ebf4fcd0d3346a1c7282bd0f7a9f0209252d7a166fd4d0e010c"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
