name = "encrypted group"
author = "encode42"
version = "1.4.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e7729e0078e890eaba6811a72a3f3698d23cc1808d62df93315003132d5ec04b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
