name = "encrypted group"
author = "encode42"
version = "1.6.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d995fc9b5482a12398807508147e0b567a3f05f61c7633f32baef0362b571a7b"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
