name = "encrypted group"
author = "encode42"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "863cb1e8d7c1db8df0d1787a5aba8cef67af8eba44121919274818a44d00499f"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
datapack-folder = "configureddefaults/paxi/datapacks"
