name = "encrypted group"
author = "encode42"
version = "1.9.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "acfe1d3f74a8bab76f18d71a2b044c83df11488cd7076644eefe2488390c69e1"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
