name = "encrypted group"
author = "encode42"
version = "1.5.0-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5ad77cf98a9afc403d12800a1e5d7025bc6f2ce169032ee96d1fe8814d6185b6"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
