name = "encrypted group"
author = "encode42"
version = "1.5.2-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c6cb80351ece6084392baf707edee6c078577aff3359dcdfe197fa0019b4e221"

[versions]
fabric = "0.15.3"
minecraft = "1.20.1"
