name = "encrypted group"
author = "encode42"
version = "2.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1a2273a7eddba7988d6479a8b76d268a2ef2a5c97eb0aa565e968c0f48e91289"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
datapack-folder = "configureddefaults/paxi/datapacks"
