name = "encrypted group"
author = "encode42"
version = "2.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3947b9df780c984179c7d04ca5785581eaa785c7ed6419246401861d616b8e0b"

[versions]
minecraft = "1.20.1"
neoforge = "47.1.101"

[options]
datapack-folder = "configureddefaults/paxi/datapacks"
