name = "encrypted group"
author = "encode42"
version = "1.10.1-SNAPSHOT"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "40eb285d292bc299189d12fe024c018aaa56b745234a5148bca35fcb6183197a"

[versions]
fabric = "0.15.6"
minecraft = "1.20.1"
