# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				bee = true
				axolotl = true
				egg = true
				arrow = true
				cow = true
				allay = true
				skeleton = true
				bat = true
				frog = true
				camel = true
				experience_bottle = true
				rabbit = true
				firework_rocket = true
				armor_stand = true
				giant = true
				drowned = true
				experience_orb = true
				dolphin = true
				item = true
				turtle = true
				salmon = true
				goat = true
				furnace_minecart = true
				ender_dragon = true
				evoker = true
				glow_squid = true
				glow_item_frame = false
				squid = true
				creeper = true
				enderman = true
				dragon_fireball = true
				chicken = true
				donkey = true
				evoker_fangs = true
				chest_minecart = true
				fox = true
				slime = true
				iron_golem = true
				area_effect_cloud = true
				blaze = true
				end_crystal = true
				endermite = true
				cat = true
				zombie = true
				ender_pearl = true
				ghast = true
				sheep = true
				player = true
				eye_of_ender = true
				villager = true
				zombie_villager = true
				block_display = true
				elder_guardian = true
				chest_boat = true
				boat = true
				polar_bear = true
				falling_block = true
				cave_spider = true
				cod = true
				witch = true
				spider = true
				command_block_minecart = true

			[light_sources.settings.entities.earthtojavamobs]
				piebald_pig = true
				dairy_cow = true
				harelequin_rabbit = true
				pink_footed_pig = true
				pinto_cow = true
				cookie_cow = true
				flecked_sheep = true
				cream_cow = true
				spotted_pig = true
				fancy_chicken = true
				skeleton_wolf = true
				gold_crested_chicken = true
				mottled_pig = true
				bold_striped_rabbit = true
				wooly_cow = true
				muddy_pig = true
				sunset_cow = true
				vested_rabbit = true
				sooty_pig = true
				skewbald_chicken = true
				patched_sheep = true
				pale_pig = true
				lobber_zombie = true

			[light_sources.settings.entities.myloot]
				loot_chest_minecart = true

			[light_sources.settings.entities.friendsandfoes]
				iceologer = true
				rascal = true

			[light_sources.settings.entities.wilderwild]
				firefly = true

			[light_sources.settings.entities.wildlife]
				spicebush_butterfly = true
				bettafish = true
				koi = true
				bluegill = true
				possum = true
				ladybug = true
				morpho_butterfly = true
				sanddollar = true
				catfish = true
				robin = true
				goldfish = true
				king_snake = true
				rainbow_trout = true
				glasswing_butterfly = true
				sparrow = true
				lark = true
				starfish = true
				phoebe = true
				ant = true
				stickbug = true
				prawn = true
				grass_snake = true
				bluebird = true
				sunflowerbeetle = true
				horseshoecrab = true
				cricket = true
				clam = true
				spider = true
				white_eye = true
				crab = true

