enableSodiumMenu = true
cloudCulling = true
signTextCulling = true
rainCulling = true
useBlockStateCulling = true
useCustomItemFrameRenderer = true
itemFrameMapCulling = true
useItemFrameLOD = true
itemFrameLODRange = 256
useItemFrame3FaceCulling = true
itemFrame3FaceCullingRange = 12.0
leavesCullingMode = "DEPTH"
leavesCullingAmount = 2
includeMangroveRoots = true
powderSnowCulling = true
entityModelCulling = false
useOnModdedBlocksByDefault = true

[modCompatibility]
reinfbarrel = true
farmersdelight = true
casualness_delight = true
nightlights = true
create_new_age = true
supplementaries = true
megacells = true
createbb = true
ubesdelight = true
suppsquared = true
chipped = true
paladins = true
create = true
festive_delight = true
frightsdelight = true
extended_drawers = true
pack_it_up = true
estrogen = true
friendsandfoes = true
runes = true
golemfirststonemod = true
minecraft = true
ends_delight = true
merequester = true
ae2 = true
railways = true
jewelry = true
milk = true
sliceanddice = true
conjuring = true
archers = true
usefulslime = true
earthtojavamobs = true
wilderwild = true
xercamusic = true
myloot = true
muffins_slimegolem = true
a_man_with_plushies = true
create_so = true
expandeddelight = true
disenchanter = true
spell_engine = true
