name: Publish

on:
  workflow_dispatch:
    inputs:
      name:
        description: "What to name the update"
        type: string
        required: false

      releaseChannel:
        description: "Which stability channel to release the mod pack through"
        type: choice
        options:
          - release
          - beta
          - alpha
        default: "release"

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: "1.19"

    - name: Install packwiz
      run: go install github.com/packwiz/packwiz@latest

    - name: Set up Packwiz cache
      uses: actions/cache@v3
      with:
        path: ~/.cache/packwiz/cache/
        key: ${{ runner.os }}-packwiz-store
        restore-keys: ${{ runner.os }}-packwiz-store

    - name: Drop snapshot label
      id: version
      run: |
        sed -i 's/\(version = ".*\)-SNAPSHOT\("\)/\1\2/' pack.toml
        echo "VERSION=$(cat pack.toml | grep "version =" | sed 's/version = "\(.*\)"/\1/')" >> $GITHUB_OUTPUT

    - name: Build Modrinth pack
      run: |
        mkdir build
        packwiz modrinth export --output build/encrypted_group-${{ steps.version.outputs.VERSION }}.mrpack

    - name: Get commits since last tag
      id: commits
      uses: simbo/changes-since-last-release-action@v1
      with:
        line-prefix: "- "
        include-hashes: false

    - name: Publish
      uses: Kir-Antipov/mc-publish@v3.3
      with:
        github-tag: ${{ steps.version.outputs.VERSION }}
        github-token: ${{ secrets.GITHUB_TOKEN }}
        github-prerelease: ${{ inputs.releaseChannel != 'release' }}

        modrinth-id: ck6J9pZQ
        modrinth-token: ${{ secrets.MODRINTH_UPLOAD_TOKEN }}

        name: ${{ inputs.name != '' && inputs.name || steps.version.outputs.VERSION }}
        version: ${{ steps.version.outputs.VERSION }}
        version-type: ${{ inputs.releaseChannel }}
        loaders: fabric
        game-versions: 1.20.1

        files: build/*.mrpack
        changelog: ${{ steps.commits.outputs.log }}

        fail-mode: warn
